# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mina', '0004_customer_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='booking',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
