# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mina', '0008_auto_20171023_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_student',
            field=models.BooleanField(default=True),
        ),
    ]
